apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/checkoutservice
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOGUE_SERVICE_ADDR
              value: "productcatalogue:3550"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice:8080"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice:50051"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
