apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: service
          image: gcr.io/google-samples/microservices-demo/frontend
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOGUE_SERVICE_ADDR
              value: "Product-Catalogue:3550"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendationservice:8080"
            - name: AD_SERVICE_ADDR
              value: "adservice:9555"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutservice:5050"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
